apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-sync-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-sync
  template:
    metadata:
      labels:
        app: solar-sync
    spec:
      containers:
      - name: solar-sync-container
        image: solar-sync-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000

