apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: solar-sync-ingress

spec:
  rules:
  - host: solar.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: solar-sync-service
            port:
              number: 80
