name: Solar Grid CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t solar-sync-app .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Run Unit Test (Basic Check)
      run: |
        echo "Tests Passed"

  push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v3

    - name: Login DockerHub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push With Retry
      run: |
        docker tag solar-sync-app ${{ secrets.DOCKER_USERNAME }}/solar-sync-app:latest
        for i in 1 2 3
        do
          docker push ${{ secrets.DOCKER_USERNAME }}/solar-sync-app:latest && break
          echo "Retrying push..."
          sleep 15
        done

  deploy:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - uses: actions/checkout@v3

    - name: Deploy To Kubernetes
      run: |
        kubectl apply -f k8s/
